main: de.richtigeralex.amongus.AmongUs
name: "AmongUs"
author: "RichtigerAlex"
version: "0.0.5-SNAPSHOT"
api-version: "1.17"

softdepend: [HolographicDisplays]

commands:
  r:
    description: A command to get ready
    aliases: ready
  createMap:
    description: Create a new map
  voteMap:
    description: Vote for a Map in Lobby
  taskLocation:
    description: Setup Locations for Tasks